#!/bin/bash
# PostgreSQL initialisatie voor NOVA v2
# Maakt non-root user aan voor N8n

set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER $POSTGRES_NON_ROOT_USER WITH PASSWORD '$POSTGRES_NON_ROOT_PASSWORD';
    GRANT ALL PRIVILEGES ON DATABASE $POSTGRES_DB TO $POSTGRES_NON_ROOT_USER;
    GRANT CREATE ON SCHEMA public TO $POSTGRES_NON_ROOT_USER;
    ALTER DATABASE $POSTGRES_DB OWNER TO $POSTGRES_NON_ROOT_USER;
EOSQL

echo "PostgreSQL NOVA v2 initialized successfully"
