"""H12: Generate living documentation from agent source code.

Scans all agents in v2_services/ and generates:
- docs/AGENTS.md : master index with health endpoints and descriptions
- docs/API_REFERENCE.md : all endpoints per agent with parameters
"""
from __future__ import annotations

import ast
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SERVICES = ROOT / "v2_services"
DOCS = ROOT / "docs"


def extract_agent_info(agent_dir: Path) -> dict | None:
    main_py = agent_dir / "main.py"
    if not main_py.exists():
        return None

    code = main_py.read_text(encoding="utf-8", errors="replace")

    title_m = re.search(r'FastAPI\([^)]*title\s*=\s*"([^"]+)"', code)
    version_m = re.search(r'FastAPI\([^)]*version\s*=\s*"([^"]+)"', code)
    docstring_m = re.search(r'^"""(.*?)"""', code, re.DOTALL)

    title = title_m.group(1) if title_m else agent_dir.name
    version = version_m.group(1) if version_m else "?"
    docstring = docstring_m.group(1).strip().split("\n")[0] if docstring_m else ""

    endpoints = []
    for m in re.finditer(r'@app\.(get|post|put|delete|patch)\(\s*"([^"]+)"', code):
        method = m.group(1).upper()
        path = m.group(2)
        func_m = re.search(rf'@app\.{m.group(1)}\("{re.escape(path)}"[^)]*\)\s*\n(?:async )?def (\w+)', code)
        func_name = func_m.group(1) if func_m else "?"
        endpoints.append({"method": method, "path": path, "function": func_name})

    models = []
    for m in re.finditer(r'class (\w+)\(BaseModel\)', code):
        models.append(m.group(1))

    has_tests = (agent_dir / "tests").exists() and any((agent_dir / "tests").glob("test_*.py"))

    return {
        "name": agent_dir.name,
        "title": title,
        "version": version,
        "docstring": docstring,
        "endpoints": endpoints,
        "models": models,
        "has_tests": has_tests,
    }


def generate():
    DOCS.mkdir(exist_ok=True)
    agents = []
    for d in sorted(SERVICES.iterdir()):
        if not d.is_dir():
            continue
        info = extract_agent_info(d)
        if info:
            agents.append(info)

    lines = ["# NOVA v2 — Agent Index", "", f"> Auto-generated by `scripts/generate_docs.py` — {len(agents)} agents", ""]
    lines.append("| # | Agent | Version | Endpoints | Tests | Description |")
    lines.append("|---|-------|---------|-----------|-------|-------------|")
    for i, a in enumerate(agents, 1):
        test_badge = "yes" if a["has_tests"] else "no"
        lines.append(f"| {i} | `{a['name']}` | {a['version']} | {len(a['endpoints'])} | {test_badge} | {a['docstring'][:60]} |")
    lines.append("")
    lines.append("## Quick Health Check")
    lines.append("```bash")
    lines.append("# From inside the Docker network:")
    for a in agents:
        health = [e for e in a["endpoints"] if e["path"] == "/health"]
        if health:
            port_m = re.search(r'(\d+)', a["name"])
            lines.append(f"curl http://{a['name'].replace('_', '-')}:81{port_m.group(1) if port_m else '??'}/health")
    lines.append("```")
    lines.append("")

    (DOCS / "AGENTS.md").write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {DOCS / 'AGENTS.md'} ({len(agents)} agents)")

    ref_lines = ["# NOVA v2 — API Reference", "", f"> {len(agents)} agents, auto-generated", ""]
    for a in agents:
        ref_lines.append(f"## {a['title']} (`{a['name']}`)")
        ref_lines.append(f"Version: {a['version']}")
        ref_lines.append("")
        if a["docstring"]:
            ref_lines.append(f"> {a['docstring']}")
            ref_lines.append("")
        ref_lines.append("| Method | Path | Function |")
        ref_lines.append("|--------|------|----------|")
        for ep in a["endpoints"]:
            ref_lines.append(f"| {ep['method']} | `{ep['path']}` | `{ep['function']}` |")
        ref_lines.append("")
        if a["models"]:
            ref_lines.append(f"**Models:** {', '.join(f'`{m}`' for m in a['models'])}")
            ref_lines.append("")

    (DOCS / "API_REFERENCE.md").write_text("\n".join(ref_lines), encoding="utf-8")
    print(f"Wrote {DOCS / 'API_REFERENCE.md'}")


if __name__ == "__main__":
    generate()
